spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##itbank
    password: it
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시점에 테이블을 drop하고, 다시 생성한다
    properties:
      hibernate:
#        show_sql: true # System.out에 하이버네이트 실행 SQL을 남긴다
        format_sql: true # SQL 쿼리 정렬해서 알아보기 좋게 정렬한다.
        default_batch_fetch_size: 1000 # 글로벌로 fetch사이즈를 걸어버린다.

logging:
  level:
#    org.hibernate.SQL: off  # logger를 통해 하이버네이트 실행 SQL을 남기는 것을 끈다.
    org.hibernate.SQL: debug  # logger를 통해 하이버네이트 실행 SQL을 남긴다
    org.hibernate.type: trace