spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##itbank
    password: it
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create  # ?????? ?? ??? ???? drop??, ?? ????
    properties:
      hibernate:
        show_sql: true # System.out? ?????? ?? SQL? ???
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  # logger? ?? ?????? ?? SQL? ???
    org.hibernate.type: trace